
name: Deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: POST
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: https://hookb.in/Xkk01PDgdOFDYMQQY8VG
          data: "{\"module\":\"frontend\"}"
