
name: Deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: POST
        if: github.event.pull_request.merged
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ secrets.DEPLOY_URL }}
          data: "{'module':'frontend'}"
